jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

language: python
python:
    - 3.6
    - 3.7
    - 3.8
    #- pypy3.6-7.1.1

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get update -qq          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew install awscli          ; fi

cache: pip

install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - python setup.py install

script:
  - tox
  - cm -h

notifications:
  email:
    recipients:
      - giuseppedilena92@gmail.com
    on_success: never
    on_failure: never