jobs:
  include:
    - os: linux
      dist: bionic

language: python
python:
    - 3.7
    - 3.8
    #- pypy3.6-7.1.1

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

cache: pip

install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - python setup.py install

script:
  - tox
  - cm -h

notifications:
  email:
    recipients:
      - giuseppedilena92@gmail.com
    on_success: never