jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

language: python
python:
    - 3.6
    - 3.7
    - 3.8
    #- pypy3.6-7.1.1

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - python setup.py install

script:
  - echo 1


notifications:
  email:
    recipients:
      - giuseppedilena92@gmail.com
    on_success: never
    on_failure: never