jobs:
  include:
    - os: linux
      dist: bionic

language: python
python:
    - 3.6
    - 3.7
    - 3.8
    #- pypy3.6-7.1.1

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

cache: pip

install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - python setup.py install

script:
  - tox

after_success:
  - codecov -t f9aadfe0-4412-42d2-9f39-28025e4f63a7


notifications:
  email:
    recipients:
      - giuseppedilena92@gmail.com
    on_success: never
    on_failure: never